const Expensecategories = [
  {
    label: "Clothes",
    value: 1,
    icon: "tshirt",
    backgroundColor: "#F614DF",
    backgroundColor1: "#2A69FC",
    backgroundColor2: "#14F6EE",
  },
  {
    label: "Foods",
    value: 2,
    icon: "utensils",
    backgroundColor: "#2599F1",
    backgroundColor1: "#37DBB4",
    backgroundColor2: "#3BE172",
  },
  {
    label: "Gadget",
    value: 3,
    icon: "mobile",
    backgroundColor: "#3BE172",
    backgroundColor1: "#448FF1",
    backgroundColor2: "#61B9FC",
  },
  {
    label: "Kids",
    value: 7,
    icon: "child",
    backgroundColor: "#34C8E6",
    backgroundColor1: "#4A5AE9",
    backgroundColor2: "#EC6EAD",
  },
  {
    label: "Fuel",
    value: 4,
    icon: "gas-pump",
    backgroundColor: "#EE0979",
    backgroundColor1: "#9851E9",
    backgroundColor2: "#4CA2CD",
  },
  {
    label: "Gifts",
    value: 5,
    icon: "gift",
    backgroundColor: "#F33098",
    backgroundColor1: "#F63145",
    backgroundColor2: "#F67214",
  },
  {
    label: "Holiday",
    value: 6,
    icon: "sleigh",
    backgroundColor: "#F717FF",
    backgroundColor1: "#FB6186",
    backgroundColor2: "#FB7C1B",
  },

  {
    label: "Shopping",
    value: 8,
    icon: "shopping-cart",
    backgroundColor: "#CDF138",
    backgroundColor1: "#EB9A3D",
    backgroundColor2: "#FF36A8",
  },
  {
    label: "Travel",
    value: 9,
    icon: "plane",
    backgroundColor: "#F66031",
    backgroundColor1: "#FBBB28",
    backgroundColor2: "#B3F614",
  },
];
export default Expensecategories;
